---
- hosts: devops
  become_method: sudo
  #become_user: wl
  become: yes

  vars_files:           
          - vars/vars.yml


  roles: 
          - ssh_configuration
          - firewall
          - flaskpy
          - systemd_config
          - nginx_configuration
