---
- name: Add user to sudoers
  lineinfile:
          dest: /etc/sudoers
          regexp: '^wl'
          line: 'wl ALL=(ALL) NOPASSWD: ALL'
          state: present

- name: Configure ssh_config
  lineinfile:
          dest: /etc/ssh/ssh_config
          regexp: '^PermitRootLogin'
          line: 'PermitRootLogin no'
          state: present

- name: Reread config file
  shell: systemctl reload ssh
